import AuthProvider from "@ext/components/AuthProvider";
import NavBar from "@ext/components/NavBar";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import iconPage from "./../public/logo-taskease.png";
import TanStackProvider from "./TanStackProvider";
import "./globals.css";

const inter = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "TaskEase",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TanStackProvider>
      <html lang="en">
        <head>
          <link rel="icon" href={iconPage.src} type="image/x-icon" />
        </head>
        <body className={inter.className}>
          <AuthProvider>
            <div className="flex flex-col h-screen w-screen overflow-hidden">
              <NavBar />
              {children}
            </div>
          </AuthProvider>
        </body>
      </html>
    </TanStackProvider>
  );
}
